### ISSUE TITLE
merging homonym updates

### ISSUE THREAD

**Issue by balmas** [alpheios-project/wordlist#3]
Is the WordItem just holding a reference to the homonym object that is being updated by the LexicalQuery or is it getting a copy?  Either way, I think we need to make a change to the LexicalQuery event subscribers in the Wordlist controller that update the homonym property of the WordItem objects (e.g. onHomonymReady, onDefinitionsReady, onLemmaTranslationsReady). Currently they each overwrite the entire homonym object in the WordItem, But there is no guarantee which of these events will be received first. So we either need to merge the homonym objects (if they are a copy of what is being updated by the LexicalQuery) or only set the homonym property if it isn't already defined (if is a reference). Do you agree @irina060981 ?

**Comment by irina060981** [comment]
I was thinking about it and finally I have created overwrite strategy with the following steps:

First we could receive two events onTextQuoteSelectorCreated and OnHomonymReady (the first could be absent if we a regetting a targetword from a lookup field).

So they creates date for 3 objectStores - WordListsCommon, WordListsContext, WordListShortHomonym.
So here I used merge method to not loose context data and homonym data.

But as for the onLemmaTranslations, onDefinitionsReady, I think later for onWordUsageExamplesReady, I am using only one objectStore WordListsFullHomonym. It would be optional in future I think, a user could uncheck to store this data or environment could be RAM-low.
So here I am not inventing a wheel, because LexicalQuery merges homonym parts itself. So everytime I recieve an event with homonym - I re-save it to wordItem and re-save it to WordListsFullHomonym.
And I am not doing any additional analysis for merging it again inside wordListController.

I think it should be low-cost for RAM and for time, and make data to be consistent on different steps. What do you think?

**Comment by balmas** [comment]
I guess my concern was about timing and whether we can be guaranteed that the wordlist controller receives and handles events in the same order in which they are issued.

E.g. 
LexicalQuery fires (1) HomonymReady with just short definitions (2) FullDefsReady with full definitions added (3) LemmaTranslations Ready with translations added.

If it's possible for the WordlistController to process these in a different order than they are fired then it could do something like this, in an extreme case

LemmaTranslationsReady (3) received - homonym gets saved with full definitions and translations
FullDefs Ready (2) received - homonym gets saved without translations 
Homomyn Ready (1) received - homonym gets saved without either full definitions or translations

**Comment by irina060981** [comment]
According to LexicalQuery the order is the following:

119     LexicalQuery.evt.HOMONYM_READY.pub(this.homonym) 

122     let adapterTranslationRes = yield ClientAdapters.lemmatranslation.alpheios({

133     LexicalQuery.evt.LEMMA_TRANSL_READY.pub(this.homonym)

136     let adapterConcordanceRes = yield ClientAdapters.wordusageExamples.concordance({

146      LexicalQuery.evt.WORD_USAGE_EXAMPLES_READY.pub(adapterConcordanceRes.result)

151       let adapterLexiconResShort = yield ClientAdapters.lexicon.alpheios({

So first tufts adapter is ready and LexicalQuery.evt.HOMONYM_READY is sent
only after that 
lemmaTranslation
wordUsage
lexicon (both short and full)
could return there result.
and all of them stores data in different segments of homonym
and each step re-saves data to WordListFullHomonym 

So there is no merging conflicts here.
